DATA_DIR: /home/zhucc/stomata_index/frcnn_pytorch/datacom
K_FOLD: 5
SEED: 2021
batch_size: 16
checkepoch: 1
checkpoint: 0
checkpoint_epoch_interval: 1
checksession: 1
class_agnostic: false
cuda: true
dataset: pascal_voc_datacom
device: 0,3
disp_interval: 2
exp_group: datacom
imdb_name: voc_2007_train
imdbval_name: voc_2007_test
k_fold: 4
large_scale: false
lr: 0.0005
lr_decay_gamma: 0.5
lr_decay_step: 20
mGPUs: true
max_epochs: 20
net: res101
num_workers: 8
optimizer: adam
resume: false
save_dir: models
session: 1
set_cfgs:
- ANCHOR_SCALES
- '[4, 8, 16]'
- ANCHOR_RATIOS
- '[0.5,1,2]'
- MAX_NUM_GT_BOXES
- '100'
start_epoch: 1
use_tfboard: true
val_imdb_name: voc_2007_val
