dir_dataset: 'data/'
dir_img: 'data/imgs/'
dir_augs: 'data/augs/'
dir_mask: 'data/masks/'
dir_checkpoint: 'checkpoints'

seed: 2021
# 轮次
epochs: 200
K_FOLD: 5
# 批次大小
batch_size: 8
# 学习率
lr: 0.0001
# 设置GPU
gpus: "1,3"
# 加载预模型
load: False
# 缩放大小
inputsize: 512
scale: 1
# 优化器
optim: 'adam'
# 验证集、测试集比例
val_percent: 0.2
test_percent: 0.1

pos_w: 1
save_cp: True
checkpoint_epoch_interval: 1
img_scale: 1
n_channels: 1
n_classes: 1
bilinear: True